# Generated by Django 4.0.6 on 2022-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
