# Generated by Django 4.0.6 on 2022-08-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='customer_dni',
            new_name='customer_DNI',
        ),
        migrations.RenameField(
            model_name='tipocliente',
            old_name='cu_type',
            new_name='customer_description',
        ),
        migrations.RenameField(
            model_name='tipocliente',
            old_name='customer_id',
            new_name='customer_type_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user_id',
        ),
    ]
