# Generated by Django 4.0.6 on 2022-08-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': True},
        ),
    ]
