# Generated by Django 4.0.6 on 2022-08-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sucursal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='branch_id',
        ),
    ]
