# Generated by Django 4.1 on 2022-08-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_sucursal_branch_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.TextField()),
                ("customer_surname", models.TextField()),
                ("customer_dni", models.TextField(db_column="customer_DNI")),
                ("dob", models.TextField(blank=True, null=True)),
                ("branch_id", models.IntegerField()),
            ],
            options={
                "db_table": "cliente",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "branch_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("address_id", models.IntegerField()),
                ("address_text", models.TextField()),
                ("posta_zip", models.TextField()),
                ("city", models.TextField()),
                ("state", models.TextField()),
                ("country", models.IntegerField()),
                ("customer_id", models.IntegerField()),
                ("employee_id", models.IntegerField()),
                ("sucursar_id", models.IntegerField()),
            ],
            options={
                "db_table": "direccion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_name", models.TextField()),
                ("employee_surname", models.TextField()),
                ("employee_hire_date", models.TextField()),
                ("employee_dni", models.TextField(db_column="employee_DNI")),
                ("branch_id", models.IntegerField()),
            ],
            options={
                "db_table": "empleado",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("card_number", models.IntegerField()),
                ("card_expire", models.IntegerField()),
                ("card_expire_date", models.IntegerField()),
                ("card_cvv", models.IntegerField()),
                ("card_type", models.TextField()),
                ("customer_id", models.IntegerField()),
            ],
            options={
                "db_table": "tarjeta",
                "managed": False,
            },
        ),
    ]
