# Generated by Django 4.1 on 2022-08-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('marca_tarjeta_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca_name', models.TextField()),
            ],
            options={
                'db_table': 'marca_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.TextField(unique=True)),
                ('card_expire_date', models.DateField()),
                ('card_cvv', models.TextField(db_column='CVV')),
                ('card_type', models.TextField()),
                ('account_id', models.IntegerField()),
                ('cardbrand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.marcatarjeta')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
    ]
